# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneword', '0003_remove_myfavorite_collect_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dislike',
            new_name='favorite',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dislike',
            new_name='favorite',
        ),
    ]
